//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrackeysBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoggerMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoggerMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrackeysBot.Resources.LoggerMessages", typeof(LoggerMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly {0} already loaded. Using cache.
        /// </summary>
        internal static string AssemblyAlreadyLoaded {
            get {
                return ResourceManager.GetString("AssemblyAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load dependency &apos;{0}&apos;.
        /// </summary>
        internal static string CouldNotLoadDependency {
            get {
                return ResourceManager.GetString("CouldNotLoadDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled plugin {0} {1}.
        /// </summary>
        internal static string DisabledPlugin {
            get {
                return ResourceManager.GetString("DisabledPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled plugin {0} {1}.
        /// </summary>
        internal static string EnabledPlugin {
            get {
                return ResourceManager.GetString("EnabledPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown when attempting to disable &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionWhenDisablingPlugin {
            get {
                return ResourceManager.GetString("ExceptionWhenDisablingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown when attempting to enable &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionWhenEnablingPlugin {
            get {
                return ResourceManager.GetString("ExceptionWhenEnablingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown when attempting to load &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionWhenLoadingPlugin {
            get {
                return ResourceManager.GetString("ExceptionWhenLoadingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown when attempting to start hosted service &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionWhenStartingService {
            get {
                return ResourceManager.GetString("ExceptionWhenStartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown when attempting to stop hosted service &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionWhenStoppingService {
            get {
                return ResourceManager.GetString("ExceptionWhenStoppingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown when attempting to unload &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionWhenUnloadingPlugin {
            get {
                return ResourceManager.GetString("ExceptionWhenUnloadingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded new assembly {0}.
        /// </summary>
        internal static string LoadedNewAssembly {
            get {
                return ResourceManager.GetString("LoadedNewAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded plugin {0} {1}.
        /// </summary>
        internal static string LoadedPlugin {
            get {
                return ResourceManager.GetString("LoadedPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No token was specified in the config file for &apos;{0}&apos;! No client will be created for this plugin..
        /// </summary>
        internal static string NoPluginToken {
            get {
                return ResourceManager.GetString("NoPluginToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin &apos;{0}&apos; was requested to load, but is already loaded. Skipping!.
        /// </summary>
        internal static string PluginAlreadyLoaded {
            get {
                return ResourceManager.GetString("PluginAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin directory &apos;{0}&apos; could not be created.
        /// </summary>
        internal static string PluginDirectoryCantBeCreated {
            get {
                return ResourceManager.GetString("PluginDirectoryCantBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin &apos;{0}&apos; requires {1} dependencies: {2}.
        /// </summary>
        internal static string PluginRequiresDependencies {
            get {
                return ResourceManager.GetString("PluginRequiresDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin version {0} and assembly version {1} do not match for &apos;{2}&apos;!.
        /// </summary>
        internal static string PluginVersionMismatch {
            get {
                return ResourceManager.GetString("PluginVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloaded plugin {0} {1}.
        /// </summary>
        internal static string UnloadedPlugin {
            get {
                return ResourceManager.GetString("UnloadedPlugin", resourceCulture);
            }
        }
    }
}
